FROM ruby:2.5.1
RUN apt-get update -qq && apt-get install -y build-essential libpq-dev
ENV APP_ROOT /app
RUN mkdir $APP_ROOT
WORKDIR $APP_ROOT
COPY Gemfile $APP_ROOT/Gemfile
COPY Gemfile.lock $APP_ROOT/Gemfile.lock
RUN bundle install
COPY . $APP_ROOT
EXPOSE  3000
CMD ["rails", "server", "-b", "0.0.0.0"]