version: '3'
services:
  app:
    container_name: video_app
    hostname: video_app
    build:
      context: video_app
      dockerfile: Dockerfile.dev
    volumes:
      - ./video_app:/usr/src/app
    command: bash -c "yarn install && yarn start"
    stdin_open: true
    tty: true
    expose:
      - 3333

  api:
    container_name: video_api
    hostname: video_api
    build:
      context: auth_api
      dockerfile: Dockerfile.dev
    environment:
      RAILS_ENV: development
      MYSQL_HOST: db
      MYSQL_USERNAME: sample
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: sample
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - ./auth_api:/app
    depends_on:
      - db
    expose:
      - 3000

  web:
    image: nginx:latest
    ports:
      - 3333:80
    volumes:
      - ./web_server/nginx/conf/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - api
      - app

  db:
    image: mysql:5.7.16
    environment:
      COMPOSE_HTTP_TIMEOUT: 3600
      MYSQL_DATABASE: sample
      MYSQL_USER: sample
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
      TZ: Japan
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci
    ports:
      - '33336:3306'
    volumes:
      - ./tmp/mysql:/var/lib/mysql

networks:
  default:
    ipam:
      config:
        - subnet: 192.168.2.0/24